# This workflow builds a .NET project using MSBuild
# For more information see: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference

name: MSBuild CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .  # Change this if your solution file is located in a subdirectory.

  # Configuration type to build (e.g., Debug, Release).
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: |
        echo "Restoring NuGet packages..."
        nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build solution
      run: |
        echo "Building solution..."
        msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }} /v:normal

    - name: Publish Output
      run: |
        echo "Publishing output..."
        msbuild /p:Configuration=${{ env.BUILD_CONFIGURATION }} /t:Publish ${{ env.SOLUTION_FILE_PATH }}
